language: java
sudo: false
git:
  depth: 100
jdk:
- oraclejdk7
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_81bc982a63a3_key -iv $encrypted_81bc982a63a3_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/3334f6f280ad6cc8a059
    on_success: change
    on_failure: always
    on_start: never
